update hooks

diff --git a/config/hooks/pre-push b/config/hooks/pre-push
--- a/config/hooks/pre-push
+++ b/config/hooks/pre-push
@@ -2,19 +2,24 @@
 
 committed_filepaths=$(git diff --stat --name-only origin/main)
 
-# https://docs.djangoproject.com/en/3.1/ref/django-admin/#makemigrations
-echo "Checking if migrations are required..."
-docker-compose run django_helper python manage.py makemigrations --check --no-input --dry-run &>/dev/null || {
-    echo "Migrations are required."; exit 1
+# If any model files have been modified, check if migrations are required.
+echo "$committed_filepaths" | grep --quiet "models" && {
+    # https://docs.djangoproject.com/en/3.1/ref/django-admin/#makemigrations
+    echo "Checking if migrations are required..."
+    docker-compose run django_helper python manage.py makemigrations --check --no-input --dry-run &>/dev/null || {
+        echo "Migrations are required."; exit 1
+    }
 }
 
-# Preprocess workflow YAML files.
-echo "Preprocessing workflow files..."
-docker-compose up github_workflow_preprocessor &>/dev/null || {
-    echo "Failed to pre-process workflow files."
-    echo "For more output, try running the following:"
-    echo "  docker-compose up github_workflow_preprocessor"
-}
-git diff --quiet .github/workflows || {
-    git add .github/workflows && git commit -m 'update workflow'
+# If workflow YAML files (for CI) have been modified, preprocess the files.
+echo "$committed_filepaths" | grep --quiet ".github/" && {
+    echo "Preprocessing workflow files..."
+    docker-compose up github_workflow_preprocessor &>/dev/null || {
+        echo "Failed to pre-process workflow files."
+        echo "For more output, try running the following:"
+        echo "  docker-compose up github_workflow_preprocessor"
+    }
+    git diff --quiet .github/workflows || {
+        git add .github/workflows && git commit -m 'update workflow'
+    }
 }
