lint frontend

diff --git a/.config/hooks/pre-commit b/.config/hooks/pre-commit
--- a/.config/hooks/pre-commit
+++ b/.config/hooks/pre-commit
@@ -4,4 +4,10 @@ poetry --help &>/dev/null && [[ -d ".venv" ]] && {
     poetry run invoke qa.autoformat
 }
 
-docker-compose up github_workflow_preprocessor
+cd frontend && npx lint-staged && cd ..
+
+docker-compose up github_workflow_preprocessor || {
+    echo "Failed to pre-process workflow files."
+    echo "For more output, try running the following:"
+    echo "  docker-compose up github_workflow_preprocessor"
+}
