redirects

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -481,23 +481,24 @@ jobs:
         password: ${{ secrets.CR_PAT }}
     - name: Create writable volume directories
       run: |
-        writable_dirs=( ".backups" ".init" "_static" "_media" )
-        for writable_dir in "${writable_dirs[@]}"; do
-          mkdir -p "$writable_dir"; {
-            sudo chown -R www-data:www-data "$writable_dir" && 
-            sudo chmod a+w -R "$writable_dir"
+        dir_names=( "db/backups" "db/init" "static" "media" )
+        for dir_name in "${dir_names[@]}"; do
+          dir_path="_volumes/${writable_dir}"
+          mkdir -p "$dir_path"; {
+            sudo chown -R www-data:www-data "$dir_path" && 
+            sudo chmod a+w -R "$dir_path"
           } || exit 1
         done
     - uses: actions/cache@v2
       id: data-cache
       with:
-        path: .init
+        path: _volumes/db/init
         key: data
     - name: Fetch data
       if: ${{ steps.data-cache.outputs.cache-hit != 'true' }}
       run: |
-        test -w .init || {
-          echo "Cannot write in .init directory."; exit 1
+        test -w _volumes/db/init || {
+          echo "Cannot write in db init directory."; exit 1
         }
         rclone --help &>/dev/null || {
           curl https://rclone.org/install.sh | sudo bash 
@@ -615,23 +616,24 @@ jobs:
         password: ${{ secrets.CR_PAT }}
     - name: Create writable volume directories
       run: |
-        writable_dirs=( ".backups" ".init" "_static" "_media" )
-        for writable_dir in "${writable_dirs[@]}"; do
-          mkdir -p "$writable_dir"; {
-            sudo chown -R www-data:www-data "$writable_dir" && 
-            sudo chmod a+w -R "$writable_dir"
+        dir_names=( "db/backups" "db/init" "static" "media" )
+        for dir_name in "${dir_names[@]}"; do
+          dir_path="_volumes/${writable_dir}"
+          mkdir -p "$dir_path"; {
+            sudo chown -R www-data:www-data "$dir_path" && 
+            sudo chmod a+w -R "$dir_path"
           } || exit 1
         done
     - uses: actions/cache@v2
       id: data-cache
       with:
-        path: .init
+        path: _volumes/db/init
         key: data
     - name: Fetch data
       if: ${{ steps.data-cache.outputs.cache-hit != 'true' }}
       run: |
-        test -w .init || {
-          echo "Cannot write in .init directory."; exit 1
+        test -w _volumes/db/init || {
+          echo "Cannot write in db init directory."; exit 1
         }
         rclone --help &>/dev/null || {
           curl https://rclone.org/install.sh | sudo bash 
