MH-210: Add Cypress to GitHub Actions (#622)
* add Cypress to GitHub Actions
* use docker-compose.test.yml
* disable image caching
* use prod data for testing

diff --git a/.github/workflows-src/integration.yml b/.github/workflows-src/integration.yml
--- a/.github/workflows-src/integration.yml
+++ b/.github/workflows-src/integration.yml
@@ -38,12 +38,11 @@ env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
   IMGUR_CLIENT_SECRET: ${IMGUR_CLIENT_SECRET}
-  MEGA_USERNAME: ${{ secrets.MEGA_USERNAME }}
-  MEGA_PASSWORD: ${{ secrets.MEGA_PASSWORD }}
   POSTGRES_HOST: postgres
   POSTGRES_DB: postgres
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
+  RCLONE_GDRIVE_SA_CREDENTIALS: ${{ secrets.RCLONE_GDRIVE_SA_CREDENTIALS }}
   SECRET_KEY: ${{ secrets.SECRET_KEY }}
   SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
   SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
@@ -63,16 +62,34 @@ env:
   X_RAPIDAPI_KEY: ${{ secrets.X_RAPIDAPI_KEY }} 
 
 jobs:
-  test-setup:
+  changed-files:
+    name: Get changed files
+    runs-on: ubuntu-latest
+    outputs:
+      added-files: ${{ steps.changed-files.outputs.added_files }}
+      deleted-files: ${{ steps.changed-files.outputs.deleted_files }}
+      modified-files: ${{ steps.changed-files.outputs.modified_files }}
+      all-changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
+    - name: Get changed files
+      id: changed-files
+      # https://github.com/tj-actions/changed-files
+      uses: tj-actions/changed-files@v1.0.1
+
+  setup-script:
     name: Test setup script
-    runs-on: ${{ matrix.os }}
+    needs: changed-files
+    if: ${{ contains(needs.changed-files.outputs.modified-files, 'setup.sh') }}
     strategy:
-      max-parallel: 3
       matrix:
         # OS options: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
         # NOTE: Services (running in Docker containers) only work on ubuntu.
         os: [ macos-latest, ubuntu-latest ]
         python-version: [ 3.9 ]
+    runs-on: ${{ matrix.os }}
     environment: dev
     env:
       TESTING: true
@@ -81,19 +98,37 @@ jobs:
       with:
         os: ${{ runner.os }}
         python-version: ${{ matrix.python-version }}
+        environment: dev
     - name: Run setup script
       run: bash setup.sh
       shell: bash
 
-  test-app:
-    name: Test application
-    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
-    runs-on: ${{ matrix.os }}
+  build:
+    name: Build image
+    runs-on: ubuntu-latest
     strategy:
       max-parallel: 3
       matrix:
-        # services (running in Docker containers) only work on ubuntu
-        os: [ ubuntu-latest ]
+        image: [ django, react, webserver ]
+    environment: test
+    steps:
+    - includes: ./.github/actions/setup
+      with:
+        os: ${{ runner.os }}
+        environment: test
+    - includes: ./.github/actions/build
+      with:
+        os: ${{ runner.os }}
+        image: ${{ matrix.image }}
+        tags: ghcr.io/modularhistory/${{ matrix.image }}:${{ github.sha }}
+        push: true
+
+  pytest:
+    name: Run backend integration tests
+    runs-on: ubuntu-latest
+    strategy:
+      max-parallel: 3
+      matrix:
         python-version: [ 3.9 ]
     services:
       postgres:
@@ -104,7 +139,7 @@ jobs:
           POSTGRES_PASSWORD: postgres
         ports:
           - 5432:5432
-        # Set health checks to wait until postgres has started
+        # Set health checks to wait until postgres has started.
         options: >-
           --health-cmd pg_isready
           --health-interval 10s
@@ -114,16 +149,17 @@ jobs:
         image: redis
         ports:
           - 6379:6379
-        # Set health checks to wait until redis has started
+        # Set health checks to wait until redis has started.
         options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
-    environment: integration
+    environment: test
     env:
       TESTING: true
     steps:
     - includes: ./.github/actions/setup
       with:
-        os: ${{ matrix.os }}
+        os: ${{ runner.os }}
         python-version: ${{ matrix.python-version }}
+        environment: test
     - name: Make sure pytest is working
       run: |
         echo "def test_pytest(): pass" > nothing.py
@@ -131,99 +167,122 @@ jobs:
     - name: Run tests
       run: poetry run invoke test --no-docker
 
+  e2e:
+    name: Run e2e tests
+    needs: [build]
+    environment: test
+    env:
+      ENVIRONMENT: test
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        browser: [ chrome ]
+        container: [ 1, 2 ]
+      max-parallel: 4
+    continue-on-error: true
+    steps:
+    - includes: ./.github/actions/setup
+      with:
+        os: ${{ runner.os }}
+        environment: test
+    - name: Login to GitHub Container Registry
+      uses: docker/login-action@v1.10.0
+      with:
+        registry: ghcr.io
+        username: ${{ github.repository_owner }}
+        password: ${{ secrets.CR_PAT }}
+    - name: Create writable volume directories
+      run: |
+        writable_dirs=( ".backups" ".init" "_static" "_media" )
+        for writable_dir in "${writable_dirs[@]}"; do
+          mkdir -p "$writable_dir"; {
+            sudo chown -R www-data:www-data "$writable_dir" && 
+            sudo chmod a+w -R "$writable_dir"
+          } || exit 1
+        done
+    - uses: actions/cache@v2
+      id: data-cache
+      with:
+        path: .init
+        key: data
+    - name: Fetch data
+      if: ${{ steps.data-cache.outputs.cache-hit != 'true' }}
+      run: |
+        test -w .init || {
+          echo "Cannot write in .init directory."; exit 1
+        }
+        rclone --help &>/dev/null || {
+          curl https://rclone.org/install.sh | sudo bash 
+        } || exit 1
+        poetry run invoke db.seed --remote
+    - name: Start up containers
+      shell: bash
+      run: |
+        shopt -s expand_aliases
+        alias compose="docker-compose -f docker-compose.yml -f docker-compose.test.yml"
+        echo "Starting containers with version $SHA ..."
+        compose up -d webserver; compose logs; echo ""; compose ps
+        [[ ! "$(compose ps)" =~ webserver ]] && exit 1
+        healthy=false; timeout=300; interval=20; waited=0
+        while [[ "$healthy" = false ]]; do
+          healthy=true; [[ "$(compose ps)" =~ (Exit|unhealthy|starting) ]] && healthy=false
+          if [[ "$healthy" = false ]]; then 
+            compose logs --tail 20; echo ""; compose ps; echo ""
+            echo "Waiting for containers (${waited}s) ..."; echo ""
+            sleep $interval; waited=$((waited + interval))
+            if [[ $waited -gt $timeout ]]; then 
+              echo "Timed out."; compose logs; exit 1
+            fi
+          fi
+        done; compose ps
+    - name: Run Cypress
+      env:
+        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+        # Pass the GitHub token to determine the unique run id necessary to re-run the checks.
+        # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: >
+        docker-compose -f docker-compose.yml -f docker-compose.test.yml run cypress
+        --browser ${{ matrix.browser }} --group "${{ matrix.browser }}"
+        --parallel --ci-build-id $GITHUB_TOKEN --record --key $CYPRESS_RECORD_KEY
+
   check-types:
     name: Check types
+    needs: changed-files
+    if: ${{ contains(needs.changed-files.outputs.modified-files, 'py') }}
     runs-on: ubuntu-latest
     strategy:
       max-parallel: 3
       matrix:
+        executable: [ mypy, pytype ]
         python-version: [ 3.9 ]
-    environment: integration
+    continue-on-error: ${{ matrix.executable == 'mypy' }}
+    environment: test
     steps:
     - 
       includes: ./.github/actions/setup
       with:
         os: ${{ runner.os }}
         python-version: ${{ matrix.python-version }}
+        environment: test
     - 
       name: Cache type stubs
       id: cache-stubs
       uses: actions/cache@v2
       with:
-        path: .pytype
-        key: ${{ matrix.python-version }}-type-stubs
+        path: .cache/${{ matrix.executable }}
+        key: ${{ matrix.python-version }}-${{ matrix.executable }}-types
+    - 
+      name: Determine args
+      id: args
+      run: |
+        if [ ${{ matrix.executable }} = mypy ]; then args="--config-file=./setup.cfg .";
+        elif [ ${{ matrix.executable }} = pytype ]; then args="--config=./setup.cfg"; fi;
+        echo "::set-output name=args::$args"
     -
       name: Run static type checker
-      run: poetry run pytype --config=./setup.cfg
-
-  build-django:
-    name: Build Django image
-    runs-on: ubuntu-latest
-    strategy:
-      max-parallel: 3
-      matrix:
-        python-version: [ 3.9 ]
-    environment: integration
-    steps:
-    - 
-      includes: ./.github/actions/setup
-      with:
-        os: ${{ runner.os }}
-        python-version: ${{ matrix.python-version }}
-    -
-      name: Inject environment vars
-      run: poetry run invoke setup.write-env-file
-    - 
-      includes: ./.github/actions/build
-      with:
-        os: ${{ runner.os }}
-        image: django
-
-  build-react:
-    name: Build React image
-    runs-on: ubuntu-latest
-    strategy:
-      max-parallel: 3
-      matrix:
-        python-version: [ 3.9 ]
-    environment: integration
-    steps:
-    - 
-      includes: ./.github/actions/setup
-      with:
-        os: ${{ runner.os }}
-        python-version: ${{ matrix.python-version }}
-    -
-      name: Inject environment vars
-      run: poetry run invoke setup.write-env-file
-    - 
-      includes: ./.github/actions/build
-      with:
-        os: ${{ runner.os }}
-        image: react
-
-  build-webserver:
-    name: Build webserver image
-    runs-on: ubuntu-latest
-    strategy:
-      max-parallel: 3
-      matrix:
-        python-version: [ 3.9 ]
-    environment: integration
-    steps:
-    - 
-      includes: ./.github/actions/setup
-      with:
-        os: ${{ runner.os }}
-        python-version: ${{ matrix.python-version }}
-    -
-      name: Inject environment vars
-      run: poetry run invoke setup.write-env-file
-    - 
-      includes: ./.github/actions/build
-      with:
-        os: ${{ runner.os }}
-        image: webserver
+      run: poetry run ${{ matrix.executable }} ${{ steps.args.outputs.args }}
 
   analyze:
     name: CodeQL Analysis
